### ISSUE TITLE
setup_features_group fucntion is not working

### ISSUE THREAD

**Issue by anderdnavarro** [simonprovost/Auto-Sklong#5]
Hi!

I'm trying to replicate your tutorial to manually select longitudinal and non_longitudinal variables ([here](https://simonprovost.github.io/scikit-longitudinal/temporal_dependency/)) but I always get an `IndexError`:

This is the code:
```python
# Load the dataset
dataset = LongitudinalDataset('/home/stroke_longitudinal.csv')
dataset_pd = pd.read_csv('/home/stroke_longitudinal.csv')
dataset_pd.head()

#	smoke_w1	smoke_w2	cholesterol_w1	cholesterol_w2	age	gender	stroke_w2
# 0	0	1	0	1	45	1	0
# 1	1	1	1	1	50	0	1
# 2	0	0	0	0	55	1	0
# 3	1	1	1	1	60	0	1
# 4	0	1	0	1	65	1	0

dataset.load_data()
dataset.load_target(target_column="stroke_w2")
dataset.load_train_test_split()
dataset.setup_features_group(
    features_group=[[0,1],[2,3]],
    non_longitudinal_features=[4,5]
)
```

And this the error:
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[20], line 5
      3 dataset.load_target(target_column="stroke_w2")
      4 dataset.load_train_test_split()
----> 5 dataset.setup_features_group(
      6     features_group=[[0,1],[2,3]],
      7     non_longitudinal_features=[4,5]
      8 )

File /usr/local/lib/python3.9/site-packages/scikit_longitudinal/data_preparation/longitudinal_dataset.py:50, in validate_feature_groups.<locals>.wrapper(*args, **kwargs)
     48 @wraps(func)
     49 def wrapper(*args, **kwargs):
---> 50     input_data = kwargs.get("input_data", None) or args[1]
     51     if input_data is not None and (isinstance(input_data, str) and input_data.lower() != "elsa"):
     52         if not isinstance(input_data, list) or not all(isinstance(group, list) for group in input_data):

IndexError: tuple index out of range
```

I also tried other datasets with the same result.

I'm using `python3.9` and these modules versions:
```bash
scikit-lexicographical-trees==0.0.4
Scikit-longitudinal==0.0.6
scipy==1.13.1
```

Thanks!!
Ander

**Comment by simonprovost** [comment]
Hi, Mate! I will respond in a few days; I am attending a conference this week. No worries, your errors are not unusual; I will explain how to correct it. In the meantime, look over here if you still want to explore. https://arc.net/l/quote/oxenhevi

Cheers,

**Comment by anderdnavarro** [comment]
Hi!

Enjoy the conference! I could solve the problem. Instead of:
```python
dataset.setup_features_group(
    features_group=[[0,1],[2,3]],
    non_longitudinal_features=[4,5]
)
```

I had to run it as:
```python
dataset.setup_features_group(
    input_data=[[0,1],[2,3]]
)
```

I think that in the `Temporal Dependency` tab of the documentation, the explanation of how to use the `setup_features_group` function is out of date, but in the `API Reference` is correct.

Thank you very much!
Ander

**Comment by simonprovost** [comment]
Hi @anderdnavarro,

Excellent observation! I need to update a lot of these things, but the API reference should be the most up to current!

The use of input_data improves long-term modularity with any type of longitudinal dataset given that every data collector simply cook longitudinal datasets the way they want we needed to have a flexible way of setting the "features group"

Cheers,

**Comment by simonprovost** [comment]
Closing for now. I intend to cite this Github Issue in the corresponding PR as soon as I can work on that.

**Comment by simonprovost** [comment]
New release `0.0.3` is now available! 🎉 The major change is the migration from `PDM` to `UV` for easier and faster installation. However, I used the opportunity to improve the documentation slightly, particularly in terms of feature list names issue in the quick start pseudo-code as you pointed out and explaining better the installation on Apple silicon-based Macs.

Have a peek at the releases and the documentation! Thanks for your help showing them out!

_Note: Will apply the same migration and doc. refactor to `Sklong` as soonish as possible!_

Cheers,
